# Install Kind
deploy_kind = ENV['DEPLOY_KIND'] || false

$script = <<-SCRIPT

# Réseau
echo "DNS=8.8.8.8" >> /etc/systemd/resolved.conf
systemctl restart systemd-resolved

apt-get update
apt-get install -y docker.io
usermod -aG docker vagrant

SCRIPT

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-24.04"
    
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/E-learning by RousselTM"]
        v.memory = 4096
        v.cpus = 4
    end
    
    #Transfert de port machine -> vm
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "k8s-kind-formation"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "k8s-kind-formation"
    end

    #Definir le hostname de la VM
    config.vm.hostname = "k8s-kind-formation"    

    config.vm.provision "shell", inline: $script

    if deploy_kind 
        config.vm.provision "shell", path: "scripts/install.sh"
    end

end